### ISSUE TITLE
What does this plugin do ?

### ISSUE THREAD

**Issue by AlliSite** [SwiftTeam-Dev/SwiftUtils#1]
What does this plugin do?

**Comment by SniperTVmc** [comment]
Hello @AlliSite! Our plugin is currently in the development stage.

We just wanted to release a first version, the 1.0.0-alpha. And as the name suggests, it's in the alpha version.
And indeed, there's nothing concrete available with the plugin other than a simple `/swiftutils` command to get various information or reload configuration files.
What's more, we'll soon be able to set up an update checking system for our plugin.
Once we release our beta version, the plugin will probably be published initially on the SpigotMC platform.

We hope we've answered your question. Also, if you have any suggestions for our plugin, we invite you to join our [discord](https://discord.gg/fSzK79TAYf), or to [open a new issue](https://github.com/SwiftTeam-Dev/SwiftUtils/issues).
